// Code generated by github.com/spacemeshos/go-scale/gen. DO NOT EDIT.

package types

import (
	"github.com/spacemeshos/go-scale"
)

func (t *CommonBody) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Address (0)
	if n, err := scale.EncodeStruct(enc, t.Address); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Selector (1)
	if n, err := scale.EncodeCompact8(enc, t.Selector); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *CommonBody) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Address (0)
	if field, n, err := scale.DecodeStruct[scale.Bytes20](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Address = field
	}

	// field Selector (1)
	if field, n, err := scale.DecodeCompact8(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Selector = field
	}

	return total, nil
}
