// Code generated by github.com/spacemeshos/go-scale/gen. DO NOT EDIT.

package types

import (
	"github.com/spacemeshos/go-scale"
)

func (t *SpawnMulti) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Type (0)
	if n, err := scale.EncodeCompact8(enc, t.Type); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Body (1)
	if n, err := scale.EncodeStruct(enc, t.Body); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpawnMulti) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Type (0)
	if field, n, err := scale.DecodeCompact8(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Type = field
	}

	// field Body (1)
	if field, n, err := scale.DecodeStruct[SpawnMultiBody](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Body = field
	}

	return total, nil
}

func (t *SpawnMultiBody) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Address (0)
	if n, err := scale.EncodeStruct(enc, t.Address); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Selector (1)
	if n, err := scale.EncodeCompact8(enc, t.Selector); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Payload (2)
	if n, err := scale.EncodeStruct(enc, t.Payload); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpawnMultiBody) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Address (0)
	if field, n, err := scale.DecodeStruct[scale.Bytes20](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Address = field
	}

	// field Selector (1)
	if field, n, err := scale.DecodeCompact8(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Selector = field
	}

	// field Payload (2)
	if field, n, err := scale.DecodeStruct[SpawnMultiPayload](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Payload = field
	}

	return total, nil
}

func (t *SpawnMultiPayload) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Template (0)
	if n, err := scale.EncodeStruct(enc, t.Template); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Keys (1)
	if n, err := scale.EncodeStructArray(enc, t.Keys); err != nil {
		return total, err
	} else {
		total += n
	}

	// field GasPrice (2)
	if n, err := scale.EncodeCompact32(enc, t.GasPrice); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Signatures (3)
	if n, err := scale.EncodeStruct(enc, t.Signatures); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpawnMultiPayload) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Template (0)
	if field, n, err := scale.DecodeStruct[scale.Bytes20](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Template = field
	}

	// field Keys (1)
	if n, err := scale.DecodeStructArray(dec, &t.Keys); err != nil {
		return total, err
	} else {
		total += n
	}

	// field GasPrice (2)
	if field, n, err := scale.DecodeCompact32(dec); err != nil {
		return total, err
	} else {
		total += n
		t.GasPrice = field
	}

	// field Signatures (3)
	if field, n, err := scale.DecodeStruct[MultiSig](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Signatures = field
	}

	return total, nil
}

func (t *MultiSig) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field SigConf (0)
	if n, err := scale.EncodeCompact8(enc, t.SigConf); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Signatures (1)
	if n, err := scale.EncodeStructArray(enc, t.Signatures); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *MultiSig) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field SigConf (0)
	if field, n, err := scale.DecodeCompact8(dec); err != nil {
		return total, err
	} else {
		total += n
		t.SigConf = field
	}

	// field Signatures (1)
	if n, err := scale.DecodeStructArray(dec, &t.Signatures); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpendMulti) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Type (0)
	if n, err := scale.EncodeCompact8(enc, t.Type); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Body (1)
	if n, err := scale.EncodeStruct(enc, t.Body); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpendMulti) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Type (0)
	if field, n, err := scale.DecodeCompact8(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Type = field
	}

	// field Body (1)
	if field, n, err := scale.DecodeStruct[SpendMultiBody](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Body = field
	}

	return total, nil
}

func (t *SpendMultiBody) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Address (0)
	if n, err := scale.EncodeStruct(enc, t.Address); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Selector (1)
	if n, err := scale.EncodeCompact8(enc, t.Selector); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Payload (2)
	if n, err := scale.EncodeStruct(enc, t.Payload); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpendMultiBody) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Address (0)
	if field, n, err := scale.DecodeStruct[scale.Bytes20](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Address = field
	}

	// field Selector (1)
	if field, n, err := scale.DecodeCompact8(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Selector = field
	}

	// field Payload (2)
	if field, n, err := scale.DecodeStruct[SpendMultiPayload](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Payload = field
	}

	return total, nil
}

func (t *SpendMultiPayload) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Arguments (0)
	if n, err := scale.EncodeStruct(enc, t.Arguments); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Nonce (1)
	if n, err := scale.EncodeStruct(enc, t.Nonce); err != nil {
		return total, err
	} else {
		total += n
	}

	// field GasPrice (2)
	if n, err := scale.EncodeCompact64(enc, t.GasPrice); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Signatures (3)
	if n, err := scale.EncodeStruct(enc, t.Signatures); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpendMultiPayload) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Arguments (0)
	if field, n, err := scale.DecodeStruct[SpendMethodArguments](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Arguments = field
	}

	// field Nonce (1)
	if field, n, err := scale.DecodeStruct[SpendNonceFields](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Nonce = field
	}

	// field GasPrice (2)
	if field, n, err := scale.DecodeCompact64(dec); err != nil {
		return total, err
	} else {
		total += n
		t.GasPrice = field
	}

	// field Signatures (3)
	if field, n, err := scale.DecodeStruct[MultiSig](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Signatures = field
	}

	return total, nil
}
