// Code generated by github.com/spacemeshos/go-scale/gen. DO NOT EDIT.

package types

import (
	"github.com/spacemeshos/go-scale"
)

func (t *Spend) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Type (0)
	if n, err := scale.EncodeCompact8(enc, t.Type); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Body (1)
	if n, err := scale.EncodeStruct(enc, t.Body); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *Spend) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Type (0)
	if field, n, err := scale.DecodeCompact8(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Type = field
	}

	// field Body (1)
	if field, n, err := scale.DecodeStruct[SpendBody](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Body = field
	}

	return total, nil
}

func (t *SpendBody) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Adress (0)
	if n, err := scale.EncodeStruct(enc, t.Adress); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Selector (1)
	if n, err := scale.EncodeCompact8(enc, t.Selector); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Payload (2)
	if n, err := scale.EncodeStruct(enc, t.Payload); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpendBody) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Adress (0)
	if field, n, err := scale.DecodeStruct[scale.Address](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Adress = field
	}

	// field Selector (1)
	if field, n, err := scale.DecodeCompact8(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Selector = field
	}

	// field Payload (2)
	if field, n, err := scale.DecodeStruct[SpendPayload](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Payload = field
	}

	return total, nil
}

func (t *SpendMethodArguments) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Recipient (0)
	if n, err := scale.EncodeStruct(enc, t.Recipient); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Amount (1)
	if n, err := scale.EncodeCompact64(enc, t.Amount); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpendMethodArguments) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Recipient (0)
	if field, n, err := scale.DecodeStruct[scale.Address](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Recipient = field
	}

	// field Amount (1)
	if field, n, err := scale.DecodeCompact64(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Amount = field
	}

	return total, nil
}

func (t *SpendNonceFields) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Counter (0)
	if n, err := scale.EncodeCompact32(enc, t.Counter); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Bitfield (1)
	if n, err := scale.EncodeCompact64(enc, t.Bitfield); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpendNonceFields) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Counter (0)
	if field, n, err := scale.DecodeCompact32(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Counter = field
	}

	// field Bitfield (1)
	if field, n, err := scale.DecodeCompact64(dec); err != nil {
		return total, err
	} else {
		total += n
		t.Bitfield = field
	}

	return total, nil
}

func (t *SpendPayload) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field Arguments (0)
	if n, err := scale.EncodeStruct(enc, t.Arguments); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Nonce (1)
	if n, err := scale.EncodeStruct(enc, t.Nonce); err != nil {
		return total, err
	} else {
		total += n
	}

	// field GasPrice (2)
	if n, err := scale.EncodeCompact32(enc, t.GasPrice); err != nil {
		return total, err
	} else {
		total += n
	}

	// field Signature (3)
	if n, err := scale.EncodeStruct(enc, t.Signature); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *SpendPayload) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field Arguments (0)
	if field, n, err := scale.DecodeStruct[SpendMethodArguments](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Arguments = field
	}

	// field Nonce (1)
	if field, n, err := scale.DecodeStruct[SpendNonceFields](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Nonce = field
	}

	// field GasPrice (2)
	if field, n, err := scale.DecodeCompact32(dec); err != nil {
		return total, err
	} else {
		total += n
		t.GasPrice = field
	}

	// field Signature (3)
	if field, n, err := scale.DecodeStruct[scale.Signature](dec); err != nil {
		return total, err
	} else {
		total += n
		t.Signature = field
	}

	return total, nil
}
