// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package nested

import (
	"github.com/spacemeshos/go-scale"
)

func (t *NestedModule) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := scale.EncodeByteSlice(enc, t.Value)
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *NestedModule) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		field, n, err := scale.DecodeByteSlice(dec)
		if err != nil {
			return total, err
		}
		total += n
		t.Value = field
	}
	return total, nil
}
