// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package nested

import (
	"github.com/spacemeshos/go-scale"
)

func (t *NestedModule) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := scale.EncodeByteSliceWithLimit(enc, t.Value, 32)
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *NestedModule) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		field, n, err := scale.DecodeByteSliceWithLimit(dec, 32)
		if err != nil {
			return total, err
		}
		total += n
		t.Value = field
	}
	return total, nil
}

func (t *Struct) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := scale.EncodeCompact64(enc, uint64(t.A))
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *Struct) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		field, n, err := scale.DecodeCompact64(dec)
		if err != nil {
			return total, err
		}
		total += n
		t.A = uint64(field)
	}
	return total, nil
}
