// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

package examples

import (
	"github.com/spacemeshos/go-scale"
)

func (t *Compact) EncodeScale(enc *scale.Encoder) (total int, err error) {
	// field U8 (0)
	if n, err := scale.EncodeCompact8(enc, t.U8); err != nil {
		return total, err
	} else {
		total += n
	}

	// field U16 (1)
	if n, err := scale.EncodeCompact16(enc, t.U16); err != nil {
		return total, err
	} else {
		total += n
	}

	// field U32 (2)
	if n, err := scale.EncodeCompact32(enc, t.U32); err != nil {
		return total, err
	} else {
		total += n
	}

	// field U64 (3)
	if n, err := scale.EncodeCompact64(enc, t.U64); err != nil {
		return total, err
	} else {
		total += n
	}

	return total, nil
}

func (t *Compact) DecodeScale(dec *scale.Decoder) (total int, err error) {
	// field U8 (0)
	if field, n, err := scale.DecodeCompact8(dec); err != nil {
		return total, err
	} else {
		total += n
		t.U8 = field
	}

	// field U16 (1)
	if field, n, err := scale.DecodeCompact16(dec); err != nil {
		return total, err
	} else {
		total += n
		t.U16 = field
	}

	// field U32 (2)
	if field, n, err := scale.DecodeCompact32(dec); err != nil {
		return total, err
	} else {
		total += n
		t.U32 = field
	}

	// field U64 (3)
	if field, n, err := scale.DecodeCompact64(dec); err != nil {
		return total, err
	} else {
		total += n
		t.U64 = field
	}

	return total, nil
}
