// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

package examples

import (
	"github.com/spacemeshos/go-scale"
)

func (t *Ex1) EncodeScale(enc *scale.Encoder) (total int, err error) {
	if n, err := scale.EncodeOption(enc, t.Option); err != nil {
		return total, err
	} else { // nolint
		total += n
	}
	if n, err := scale.EncodeBool(enc, t.Bool); err != nil {
		return total, err
	} else { // nolint
		total += n
	}
	return total, nil
}

func (t *Ex1) DecodeScale(dec *scale.Decoder) (total int, err error) {
	if field, n, err := scale.DecodeOption[Ex1](dec); err != nil {
		return total, err
	} else { // nolint
		total += n
		t.Option = field
	}
	if field, n, err := scale.DecodeBool(dec); err != nil {
		return total, err
	} else { // nolint
		total += n
		t.Bool = field
	}
	return total, nil
}
