// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

package examples

import (
	"github.com/spacemeshos/go-scale"
)

func (t *ImportedB) EncodeScale(enc *scale.Encoder) (total int, err error) {
	if n, err := scale.EncodeStructArray(enc, t.List[:]); err != nil {
		return total, err
	} else { // nolint
		total += n
	}
	return total, nil
}

func (t *ImportedB) DecodeScale(dec *scale.Decoder) (total int, err error) {
	if n, err := scale.DecodeStructArray(dec, t.List[:]); err != nil {
		return total, err
	} else { // nolint
		total += n
	}
	return total, nil
}
