// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package examples

import (
	"github.com/spacemeshos/go-scale"
	"github.com/spacemeshos/go-scale/examples/nested"
)

func (t *NestedStructSlice) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := scale.EncodeStructSlice(enc, t.Value)
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *NestedStructSlice) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		field, n, err := scale.DecodeStructSlice[nested.Struct](dec)
		if err != nil {
			return total, err
		}
		total += n
		t.Value = field
	}
	return total, nil
}
