// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package examples

import (
	"github.com/spacemeshos/go-scale"
)

func (t *NestedStructNoImport) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := t.Value.EncodeScale(enc)
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *NestedStructNoImport) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		n, err := t.Value.DecodeScale(dec)
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}
