// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package examples

import (
	"github.com/spacemeshos/go-scale"
	"github.com/spacemeshos/go-scale/examples/nested"
)

func (t *NestedTypeAliasWithImport) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := scale.EncodeStringWithLimit(enc, string(t.Value), 20)
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *NestedTypeAliasWithImport) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		field, n, err := scale.DecodeStringWithLimit(dec, 20)
		if err != nil {
			return total, err
		}
		total += n
		t.Value = nested.StringAlias(field)
	}
	return total, nil
}
