// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package examples

import (
	"github.com/spacemeshos/go-scale"
)

func (t *StructWithNonLocalField) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := scale.EncodeStringWithLimit(enc, string(t.Name), 20)
		if err != nil {
			return total, err
		}
		total += n
	}
	if !enc.Local() {
		n, err := scale.EncodeStringWithLimit(enc, string(t.SomeID), 20)
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *StructWithNonLocalField) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		field, n, err := scale.DecodeStringWithLimit(dec, 20)
		if err != nil {
			return total, err
		}
		total += n
		t.Name = string(field)
	}
	if !dec.Local() {
		field, n, err := scale.DecodeStringWithLimit(dec, 20)
		if err != nil {
			return total, err
		}
		total += n
		t.SomeID = string(field)
	}
	return total, nil
}
