// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

package examples

import (
	"github.com/spacemeshos/go-scale"
)

func (t *Options) EncodeScale(enc *scale.Encoder) (total int, err error) {
	if n, err := scale.EncodeOption(enc, t.ArrayPtr); err != nil {
		return total, err
	} else {
		total += n
	}
	if n, err := scale.EncodeOption(enc, t.SlicePtr); err != nil {
		return total, err
	} else {
		total += n
	}
	return total, nil
}

func (t *Options) DecodeScale(dec *scale.Decoder) (total int, err error) {
	if field, n, err := scale.DecodeOption[array](dec); err != nil {
		return total, err
	} else {
		total += n
		t.ArrayPtr = field
	}
	if field, n, err := scale.DecodeOption[slice](dec); err != nil {
		return total, err
	} else {
		total += n
		t.SlicePtr = field
	}
	return total, nil
}
