// Code generated by github.com/spacemeshos/go-scale/scalegen. DO NOT EDIT.

// nolint
package examples

import (
	"github.com/spacemeshos/go-scale"
)

func (t *Options) EncodeScale(enc *scale.Encoder) (total int, err error) {
	{
		n, err := scale.EncodeOption(enc, t.ArrayPtr)
		if err != nil {
			return total, err
		}
		total += n
	}
	{
		n, err := scale.EncodeOption(enc, t.SlicePtr)
		if err != nil {
			return total, err
		}
		total += n
	}
	return total, nil
}

func (t *Options) DecodeScale(dec *scale.Decoder) (total int, err error) {
	{
		field, n, err := scale.DecodeOption[array](dec)
		if err != nil {
			return total, err
		}
		total += n
		t.ArrayPtr = field
	}
	{
		field, n, err := scale.DecodeOption[slice](dec)
		if err != nil {
			return total, err
		}
		total += n
		t.SlicePtr = field
	}
	return total, nil
}
